### ISSUE TITLE
translation mistake

### ISSUE THREAD

**Issue by sls1005** [alainsaas/wenyan#1]
吾（I）嘗（have）觀（read/look）「「腳本祕術」」之書（the book of "腳本祕術"）。 方（thus）悟（understand）「腳本祕術」之義（the meaning of "腳本祕術"）。

So it means "I have read the book of '腳本祕術', thus I understood the meaning of '腳本祕術'."

The meaning of characters in Classical Chinese is different from that in modern Chinese.

**Comment by alainsaas** [comment]
Thanks. Note taken if I make a new version.
